// <auto-generated />
using BazaTest1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BazaTest1.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210409102138_ludziki")]
    partial class ludziki
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BazaTest1.ludziki", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("imie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("nazisko")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("ludziki");
                });
#pragma warning restore 612, 618
        }
    }
}
