// <auto-generated />
using System;
using BazaTest1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BazaTest1.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BazaTest1.adres", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("aders")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ludzik")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ludzik");

                    b.ToTable("adres");
                });

            modelBuilder.Entity("BazaTest1.ludziki", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("dataUrodzenia")
                        .HasColumnType("datetime");

                    b.Property<string>("imie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("nazisko")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("ludziki");
                });

            modelBuilder.Entity("BazaTest1.adres", b =>
                {
                    b.HasOne("BazaTest1.ludziki", "ludzik1")
                        .WithMany()
                        .HasForeignKey("ludzik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ludzik1");
                });
#pragma warning restore 612, 618
        }
    }
}
